services:
  - type: web
    name: nkuna-burial-society
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nkuna-db
          property: connectionString
      - key: ADMIN_EMAIL
        value: admin@nkuna.co.za
      - key: ADMIN_PASSWORD
        value: Admin123!
      - key: FLASK_ENV
        value: production